# CircleCI v2.1 Config
version: 2.1

##
# orbs
#
# Orbs used in this pipeline
##
orbs:
  anchore: anchore/anchore-engine@1.6.0
  deploy-kube: mojaloop/deployment@0.1.6

##
# defaults
#
# YAML defaults templates, in alphabetical order
##
defaults_Dependencies: &defaults_Dependencies |
  apt-get update
  apt-get install -y \
    git \
    ca-certificates \
    curl

defaults_awsCliDependencies: &defaults_awsCliDependencies |
  apk --update --no-cache add \
          python3 \
          py3-pip \
          groff \
          less \
          mailcap
  pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic

defaults_license_scanner: &defaults_license_scanner
  name: Install and set up license-scanner
  command: |
    git clone https://github.com/mojaloop/license-scanner /tmp/license-scanner
    cd /tmp/license-scanner && make build default-files set-up

##
# Executors
#
# CircleCI Executors
##
executors:
  docker-debian-with-nodejs:
    working_directory: /home/circleci/project
    docker:
      - image: node:lts-buster-slim
  machine-ubuntu-with-docker:
    machine:
      image: ubuntu-2004:202010-01

##
# Jobs
#
# A map of CircleCI jobs
##
jobs:
  deploy:
    executor: deploy-kube/helm-kube
    steps:
      - checkout
      - deploy-kube/setup_and_run:
          helm_set_values: |
            --set finance-portal.frontend.image.repository=$DOCKER_ORG/$CIRCLE_PROJECT_REPONAME \
            --set finance-portal.frontend.image.tag=$CIRCLE_TAG

##
# Workflows
#
# CircleCI Workflow config
##
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy:
          context: org-global
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(\-snapshot)?/
            branches:
              ignore:
                - /.*/
